/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WeeRouteImport } from './routes/wee'
import { Route as IndexRouteImport } from './routes/index'

const WeeRoute = WeeRouteImport.update({
  id: '/wee',
  path: '/wee',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/wee': typeof WeeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/wee': typeof WeeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/wee': typeof WeeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/wee'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/wee'
  id: '__root__' | '/' | '/wee'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WeeRoute: typeof WeeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wee': {
      id: '/wee'
      path: '/wee'
      fullPath: '/wee'
      preLoaderRoute: typeof WeeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WeeRoute: WeeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
